[build]
compiler = "clang"

[[targets]]
name = "main"
src = "./src/"
include_dir = "./src/include/"
type = "exe"
cflags = "-g -gcodeview -Wall -Wextra"
libs = "-l dbghelp -fuse-ld=lld -g -Wl,--pdb="
deps = [""]
